### ISSUE TITLE
Dev Environment support

### ISSUE THREAD

**Issue by cmays20** [openshift/console-plugin-template#13]
I am having trouble getting started on a Windows box with these instructions.  What is the preferred dev environment for this?

**Comment by mikaello** [comment]
Have you tried to use VSCode with devcontainer? See https://github.com/openshift/console-plugin-template#option-2-docker--vscode-remote-container for instructions.

**Comment by huangkaoya** [comment]
i alse have the same problem. In fact, the solution of dev in openshift-dynamic-plugin is not supported windows platform fully, just about script in package.json、init.sh，and so on. So I find that vscode dev-container is a best solution of this problem, and windows also support docker desktop with WSL2 open well.

try it, you will find it's easy.
