### ISSUE TITLE
Hot reload of plugin is broken in 4.14

### ISSUE THREAD

**Issue by iocanel** [openshift/console-plugin-template#57]
After 4.14 release of OpenShift I started experiencing issues with hot reloading of console plugin when developing.
After any change in my plugin code, I was getting a 404 when trying to access the plugin, so I had to do the full (yarn run start and yarn run start-console thing again).

Logs seems clear with no indication of a problem. After exploring the browser console I noticed that the second time browser tries to fetch the console manifest (e.g. http://localhost:9000/api/plugins/quarkus-openshift-console-plugin/plugin-manifest.json) it gets a blank response back.

After rolling back to 4.13 (by changing the start-console.sh script to use 4.13 instead of latest) the issue seems fixed.

**Comment by spadgett** [comment]
/cc @vojtechszocs @jhadvig 

This could be the same as https://issues.redhat.com/browse/OCPBUGS-24607

**Comment by Javatar81** [comment]
Had the same experience with hot reload. Changing from latest to 4.13 solved the problem.

**Comment by spadgett** [comment]
/lifecycle frozen

@vojtechszocs FYI since you own the JIRA issue.

I was testing a new plugin created with the template and the origin-console:latest image yesterday, and hot reloading was working for me. @iocanel Do you have a reproducer for us?

**Comment by spadgett** [comment]
Closing for now since https://issues.redhat.com/browse/OCPBUGS-24607 is fixed, and we haven't heard if this is still an issue or gotten a reproducer. Please reopen if you're still seeing this. Thanks!
