### ISSUE TITLE
Use ENVs during Runtime on OpenShift

### ISSUE THREAD

**Issue by sambou90** [openshift/console-plugin-template#70]
Hi there

I want to use ENVs during Runtime on OpenShift. At first sight I could not place a runtime-config.json on the Webserver which serves the Plugin.

Does anyone have experience with this and can place a hint?

Thanks and regards

**Comment by spadgett** [comment]
Hi, @sambou90. Do you simply want to load a JSON file with the configuration from your plugin's webserver? I believe you should be able to make a request using `consoleFetch` to the endpoint `/api/plugins/<plugin-name>/path/to/runtime-config.json`.

cc @jhadvig @vojtechszocs

**Comment by sambou90** [comment]
Hi @spadgett 
Very nice that works fine!
Thank you for your quick response!
